import { SalesRecord } from './types.ts';

export const INITIAL_GOAL = 18000000.00;

export const MONTHS = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago'];

export const salesRecords: SalesRecord[] = [
  // Janeiro
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 63, value: 28525.81 },
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Geovana', quantity: 186, value: 71799.20 },
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Ideglan', quantity: 6, value: 24768.00 },
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Livia', quantity: 316, value: 308315.60 },
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Martinho', quantity: 43, value: 155393.36 },
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 40, value: 47635.70 },
  { month: 'Jan', channel: 'ATACADO', salesperson: 'Valdeneth', quantity: 1, value: 364.00 },
  { month: 'Jan', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 27, value: 11717.50 },
  { month: 'Jan', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 34, value: 24140.00 },
  { month: 'Jan', channel: 'INDUSTRIA', salesperson: 'Ideglan', quantity: 6, value: 16904.81 },
  { month: 'Jan', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 90, value: 190093.74 },
  { month: 'Jan', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 10, value: 19148.00 },
  { month: 'Jan', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 10, value: 11884.00 },
  // Fevereiro
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 80, value: 70073.48 },
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Geovana', quantity: 149, value: 56351.69 },
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Ideglan', quantity: 19, value: 58385.48 },
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Livia', quantity: 263, value: 232063.48 },
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Martinho', quantity: 61, value: 181288.67 },
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 25, value: 59483.39 },
  { month: 'Fev', channel: 'ATACADO', salesperson: 'Webber', quantity: 1, value: 200.00 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 19, value: 36355.00 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 34, value: 34161.00 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Ideglan', quantity: 10, value: 73655.00 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 53, value: 61112.50 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 20, value: 67088.23 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 5, value: 5541.00 },
  { month: 'Fev', channel: 'INDUSTRIA', salesperson: 'Webber', quantity: 3, value: 10800.00 },
  // Março
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 209, value: 125493.04 },
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Geovana', quantity: 297, value: 200818.05 },
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Ideglan', quantity: 6, value: 13369.00 },
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Livia', quantity: -1, value: -243.02 },
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Martinho', quantity: 36, value: 112402.87 },
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 42, value: 83139.44 },
  { month: 'Mar', channel: 'ATACADO', salesperson: 'Valdeneth', quantity: 1, value: 16.00 },
  { month: 'Mar', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 45, value: 56601.97 },
  { month: 'Mar', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 53, value: 61715.00 },
  { month: 'Mar', channel: 'INDUSTRIA', salesperson: 'Ideglan', quantity: 7, value: 30342.00 },
  { month: 'Mar', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: -1, value: -747.00 },
  { month: 'Mar', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 17, value: 40563.00 },
  { month: 'Mar', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 21, value: 28043.00 },
  // Abril
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 35, value: 25585.64 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Geovana', quantity: 168, value: 93150.09 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Ideglan', quantity: 5, value: 20548.00 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Livia', quantity: 279, value: 219117.33 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Martinho', quantity: 39, value: 112636.00 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 37, value: 99598.70 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Valdeneth', quantity: 1, value: 280.00 },
  { month: 'Abr', channel: 'ATACADO', salesperson: 'Webber', quantity: 1, value: 3655.01 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 8, value: 18416.35 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 34, value: 52571.98 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Ideglan', quantity: 6, value: 37666.81 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 63, value: 173423.45 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 6, value: 16106.60 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 18, value: 35110.55 },
  { month: 'Abr', channel: 'INDUSTRIA', salesperson: 'Webber', quantity: 1, value: 4300.00 },
  // Maio
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 87, value: 69843.29 },
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Geovana', quantity: 164, value: 139061.00 },
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Ideglan', quantity: 11, value: 40536.64 },
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Livia', quantity: 270, value: 279267.51 },
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Martinho', quantity: 55, value: 169419.85 },
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 32, value: 57526.18 },
  { month: 'Mai', channel: 'ATACADO', salesperson: 'Webber', quantity: 8, value: 79371.12 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 17, value: 10256.97 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 41, value: 57819.37 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Ideglan', quantity: 14, value: 102394.40 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 64, value: 172868.83 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 10, value: 41845.60 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 16, value: 48679.05 },
  { month: 'Mai', channel: 'INDUSTRIA', salesperson: 'Webber', quantity: 1, value: 360.00 },
  // Junho
  { month: 'Jun', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 78, value: 210987.66 },
  { month: 'Jun', channel: 'ATACADO', salesperson: 'Geovana', quantity: 180, value: 123006.35 },
  { month: 'Jun', channel: 'ATACADO', salesperson: 'Ideglan', quantity: 9, value: 39635.55 },
  { month: 'Jun', channel: 'ATACADO', salesperson: 'Livia', quantity: 310, value: 250387.42 },
  { month: 'Jun', channel: 'ATACADO', salesperson: 'Martinho', quantity: 57, value: 181355.00 },
  { month: 'Jun', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 28, value: 57014.00 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 21, value: 10837.00 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 60, value: 62277.00 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Ideglan', quantity: 6, value: 41731.50 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 80, value: 147051.84 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 12, value: 34381.50 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 13, value: 16146.87 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Valdeneth', quantity: 1, value: 90.00 },
  { month: 'Jun', channel: 'INDUSTRIA', salesperson: 'Webber', quantity: 1, value: 15200.00 },
  // Julho
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 48, value: 125557.81 },
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Geovana', quantity: 200, value: 96584.07 },
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Livia', quantity: 303, value: 305940.21 },
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Martinho', quantity: 53, value: 192667.00 },
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Thyara', quantity: 1, value: 1050.00 },
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 35, value: 86375.95 },
  { month: 'Jul', channel: 'ATACADO', salesperson: 'Webber', quantity: 2, value: 10152.89 },
  { month: 'Jul', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 16, value: 10244.50 },
  { month: 'Jul', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 64, value: 54851.61 },
  { month: 'Jul', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 75, value: 143818.32 },
  { month: 'Jul', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 13, value: 22927.15 },
  { month: 'Jul', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 16, value: 22716.57 },
  // Agosto
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Andre Nune', quantity: 53, value: 56755.40 },
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Geovana', quantity: 202, value: 149240.99 },
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Livia', quantity: 287, value: 256016.70 },
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Martinho', quantity: 51, value: 187392.13 },
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Thyara', quantity: 1, value: 126.00 },
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Ueudison', quantity: 54, value: 151013.72 },
  { month: 'Ago', channel: 'ATACADO', salesperson: 'Webber', quantity: 4, value: 353.00 },
  { month: 'Ago', channel: 'INDUSTRIA', salesperson: 'Andre Nune', quantity: 11, value: 26525.00 },
  { month: 'Ago', channel: 'INDUSTRIA', salesperson: 'Geovana', quantity: 53, value: 44526.00 },
  { month: 'Ago', channel: 'INDUSTRIA', salesperson: 'Livia', quantity: 82, value: 156297.26 },
  { month: 'Ago', channel: 'INDUSTRIA', salesperson: 'Martinho', quantity: 12, value: 46593.40 },
  { month: 'Ago', channel: 'INDUSTRIA', salesperson: 'Ueudison', quantity: 17, value: 101421.75 },
];